simplify generics
mightyiam/bookkeeping pull request #18
Opened 2020-12-16 12:51 UTC by hardliner66

You can use default types in generics. This way the user doesn't have to type all the types.
E.g.:
```rust
let mut book = Book::<(), &str>::new(());
```

instead of:
```rust
let mut book = Book::<(), &str, (), (), ()>::new(());
```

This pull request also renames the generics so that they are easier to understand and don't need a mapping from character to description.

2020-12-17 09:16 UTC, mightyiam reviewed
Just to make sure you got  the message: I am pro the expansion of the metadata generics into full form. I am con the default types.

2020-12-17 09:19 UTC, mightyiam commented on readme.md
> +let mut book = Book::new(());
Here, the defaults are not used. You might think that they are but they're not. Here, in this call, all of the generics are inferred from usage further down the road. Had this been the last line, you would have had to specify types for the generics other than the first one (because that is inferred from that argument to `new`).

2020-12-17 09:31 UTC, hardliner66 commented on readme.md
> +let mut book = Book::new(());
Later on there are other examples where only the first few types are needed.
e.g.:
```rust
let mut Book::<(), (), &str>::new();
```

But I understand if thats not the API you want for creating a book, therefore I removed the default types.

2020-12-17 10:22 UTC, mightyiam requested changes
Almost there.

2020-12-17 10:22 UTC, mightyiam commented on readme.md
> +let mut book = Book::new(());
I would actually prefer this line not to change, as well.

2020-12-17 10:22 UTC, mightyiam commented on src/balance.rs
> +    /// # let mut book = Book::new(());
No change here, as well, please.

2020-12-17 20:49 UTC, hardliner66 commented on readme.md
> +let mut book = Book::new(());
I did revert all the type changes. The code in the comment above was just an example, the code now uses all the types again.

2020-12-17 20:57 UTC, hardliner66 commented on readme.md
> +let mut book = Book::new(());
I reverted the change to this line.

2020-12-18 11:26 UTC, mightyiam commented
I will certainly get to this, @hardliner66 .

2020-12-21 06:10 UTC, merged